sudo: false
dist: trusty

language: generic

matrix:
  include:
    - os: linux
      env:
        - MCONDA_PYTHON_MAJOR=2
        - MCONDA_PYTHON_VERSION=2.7

    - os: linux
      env:
        - MCONDA_PYTHON_MAJOR=3
        - MCONDA_PYTHON_VERSION=3.5

    - os: linux
      env:
        - MCONDA_PYTHON_MAJOR=3
        - MCONDA_PYTHON_VERSION=3.6

    - os: osx
      env:
        - MCONDA_PYTHON_MAJOR=2
        - MCONDA_PYTHON_VERSION=2.7

    - os: osx
      env:
        - MCONDA_PYTHON_MAJOR=3
        - MCONDA_PYTHON_VERSION=3.5

    - os: osx
      env:
        - MCONDA_PYTHON_MAJOR=3
        - MCONDA_PYTHON_VERSION=3.6

    # build the documentation and deploy to the gh-pages branch
    - os: linux
      env:
        - MCONDA_PYTHON_MAJOR=3
        - MCONDA_PYTHON_VERSION=3.6
        - GH_PAGES_BUILD=true
        - ENCRYPTION_LABEL=0a439a1e79c8
        - COMMIT_AUTHOR_EMAIL="deploy_build@travis-ci.com"
      addons:
        apt:
          packages:
            - pandoc

env:
  global:
    - MCONDA_VERSION="latest"
    - MCONDA_LINUX="Linux-x86_64"
    - MCONDA_OSX="MacOSX-x86_64"

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export MCONDA_OS=$MCONDA_LINUX
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export MCONDA_OS=$MCONDA_OSX
    fi
    wget "http://repo.continuum.io/miniconda/Miniconda$MCONDA_PYTHON_MAJOR-$MCONDA_VERSION-$MCONDA_OS.sh" -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda False
  - conda update -yq conda
  - conda install -y python=$MCONDA_PYTHON_VERSION numpy scipy
  - conda install -c conda-forge pyopencl

  - |
    if [[ "$GH_PAGES_BUILD" == true ]]; then
      echo "installing documentation dependencies"
      pip install .[doc]
    else
      pip install .[dev]
    fi

# command to run tests
script: 
  - |
    if [[ "$GH_PAGES_BUILD" == true ]]; then
      echo "building gh-pages documentation"
      cd doc
      bash ./deploy.sh
    else
      python -m pytest
    fi
branches:
  only:
    - master

notifications:
  email:
    on_failure: change
    on_succes: never
