name: Create versioned documentation on release

on:
  release:
    types: [published]

jobs:
  build:
    environment: dev_environment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        sudo apt-get update;
        sudo apt-get install pandoc
        python -m pip install --upgrade pip
        echo "pip install .[doc]"
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        documentation_path: doc/source
        target_path: ${{ env.RELEASE_VERSION }}
    - name: Redirect stable to new release
      run: |
          echo "Redirecting stable to newly released version " $RELEASE_VERSION
          rm -rf stable
          ln -s $RELEASE_VERSION stable
          git add stable
          git commit -m "redirect stable to new version $RELEASE_VERSION"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
