name: fair-software

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  verify:
    name: "fair-software badge check"
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - uses: benvanwerkhoven/howfairis-github-action@main
        name: Measure compliance with fair-software.eu recommendations
        env:
          PYCHARM_HOSTED: "Trick colorama into displaying colored output" 
        with:
          MY_REPO_URL: "https://github.com/${{ github.repository }}"
    
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub actions user
          author_email: action@github.com
          message: 'Update README'
          add: 'README.*'
